### ISSUE TITLE
Riemann-health not working on Ubuntu 14.10 x64 vmlinuz-3.16.0-28-generic

### ISSUE THREAD

**Issue by peterneubauer** [aphyr/riemann-tools#103]
Hi there,
just provisioned a new Digital Ocean machine to monitor with Riemann-health (v 0.2.5), but I get a (parsing?) error:
````
NoMethodError undefined method `map' for #<Riemann::Event:0x000000011ab930>
/var/lib/gems/2.1.0/gems/riemann-client-0.2.3/lib/riemann/event.rb:179:in `initialize'
/var/lib/gems/2.1.0/gems/beefcake-1.1.0.pre1/lib/beefcake.rb:287:in `new'
/var/lib/gems/2.1.0/gems/beefcake-1.1.0.pre1/lib/beefcake.rb:287:in `block (2 levels) in assign'
/var/lib/gems/2.1.0/gems/beefcake-1.1.0.pre1/lib/beefcake.rb:286:in `map'
/var/lib/gems/2.1.0/gems/beefcake-1.1.0.pre1/lib/beefcake.rb:286:in `block in assign'
/var/lib/gems/2.1.0/gems/beefcake-1.1.0.pre1/lib/beefcake.rb:262:in `each'
/var/lib/gems/2.1.0/gems/beefcake-1.1.0.pre1/lib/beefcake.rb:262:in `assign'
/var/lib/gems/2.1.0/gems/beefcake-1.1.0.pre1/lib/beefcake.rb:242:in `initialize'
/var/lib/gems/2.1.0/gems/riemann-client-0.2.3/lib/riemann/client.rb:60:in `new'
/var/lib/gems/2.1.0/gems/riemann-client-0.2.3/lib/riemann/client.rb:60:in `<<'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/lib/riemann/tools.rb:69:in `report'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/bin/riemann-health:65:in `alert'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/bin/riemann-health:97:in `report_pct'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/bin/riemann-health:146:in `linux_memory'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/bin/riemann-health:269:in `call'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/bin/riemann-health:269:in `tick'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/lib/riemann/tools.rb:94:in `block in run'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/lib/riemann/tools.rb:92:in `loop'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/lib/riemann/tools.rb:92:in `run'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/lib/riemann/tools.rb:9:in `run'
/var/lib/gems/2.1.0/gems/riemann-tools-0.2.5/bin/riemann-health:280:in `<top (required)>'
/usr/local/bin/riemann-health:23:in `load'
/usr/local/bin/riemann-health:23:in `<main>'
````
My /proc/cpuinfo looks like this:

```

cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 2
model name	: QEMU Virtual CPU version 1.0
stepping	: 3
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni vmx cx16 popcnt hypervisor lahf_lm
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 2
model name	: QEMU Virtual CPU version 1.0
stepping	: 3
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 4096 KB
physical id	: 1
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni vmx cx16 popcnt hypervisor lahf_lm
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 2
model name	: QEMU Virtual CPU version 1.0
stepping	: 3
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 4096 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni vmx cx16 popcnt hypervisor lahf_lm
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 2
model name	: QEMU Virtual CPU version 1.0
stepping	: 3
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 4096 KB
physical id	: 3
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni vmx cx16 popcnt hypervisor lahf_lm
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48

````

and 

````
 cat /proc/meminfo
MemTotal:        8176324 kB
MemFree:         7780660 kB
MemAvailable:    7867088 kB
Buffers:          143664 kB
Cached:            68108 kB
SwapCached:            0 kB
Active:           208076 kB
Inactive:          24996 kB
Active(anon):      21388 kB
Inactive(anon):      256 kB
Active(file):     186688 kB
Inactive(file):    24740 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                68 kB
Writeback:             0 kB
AnonPages:         21316 kB
Mapped:            12348 kB
Shmem:               328 kB
Slab:             101452 kB
SReclaimable:      87852 kB
SUnreclaim:        13600 kB
KernelStack:        1760 kB
PageTables:         2884 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4088160 kB
Committed_AS:      71440 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       16804 kB
VmallocChunk:   34359711340 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       34804 kB
DirectMap2M:     8353792 kB
````

**Comment by aphyr** [comment]
Thanks Peter; I believe this is a bug associated with Ruby 2.x but haven't figured out why yet. Tanj reported a similar problem in IRC this morning, which makes me think the change may have been recent.

**Comment by peterneubauer** [comment]
Yeah,
might be, 0.2.5 works good on my Mac.

The ruby version:

````
ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
````

**Comment by pschrammel** [comment]
downgrade beefcake to 1.0.0

**Comment by peterneubauer** [comment]
Is that working then with a downgraded beefcake?

**Comment by pschrammel** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Works for me at least.

- ----- Originale Nachricht -----
Von: Peter Neubauer <notifications@github.com>
Gesendet: 02.02.2015 - 16:21
An: aphyr/riemann-tools <riemann-tools@noreply.github.com>
Betreff: Re: [riemann-tools] Riemann-health not working on Ubuntu 14.10 x64 vmlinuz-3.16.0-28-generic (#103)

> Is that working then with a downgraded beefcake?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/aphyr/riemann-tools/issues/103#issuecomment-72474549

-----BEGIN PGP SIGNATURE-----
Version: BCPG v1.47

iQJGBAEBAgAwBQJUz72EKRxQZXRlciBTY2hyYW1tZWwgPHBldGVyLnNjaHJhbW1l
bEBnbXguZGU+AAoJEHBsXR3UqtsxO74P/0s2TLJ4NwmLAOQHPY5AlhET+FdO8R4R
chGxWvUmLC+vVvbEZvBt9zrVsoj5u21Eci5j9+TOFIAdpa7eaOG61meh9SOOZkmj
sYfEjgObFpBSZZJAHzrnt+6qQ7ebx9SR52cdizTueL1xD9mjS1OVRiBxdW6l6ugu
PvjieJcZhQAOKLf9xHCv0RmhnZ/pxGeCUjopzWX09PmWDIej4DF4B1bCjtNFgYBC
TeRDluOuoeqh3AwTM5H3+1uWrDs9T/fS6NlvCgGODJVPIh8eTituLwjVoPBo2rA8
ptpB9EpLCf6Dq2Tnt+hOICdbxm1/lL6yPcxhL2Kn6+SbUMZToSlckk6Xo5Pme28/
GWXFDpWsZM+VPal5ODfxAxBo/GAsK1oSSGA8Yy4CLv29/jXEP7FL8RAKdkLaW7OR
nLWw7YVQrq87jdghiDeuuTWteD7tp+TWELf0YexsoZIb/HHe2eajCg7JYYxipmvd
zdOoRAsxEsrRHCakdzxR2BPE1W67+/w76aRrf5hLL7Uj0WzHSorDhix1j86FiYUc
vv0R9OYL9P4D89nrevQ5cir7rfRZ64f1zOYr/7h+oYMiP84gllwmDqrDmTPu+Wnw
7/FPQI7R7DsC15E29UqAXwSQxx2Z+7nXHpQlTIqw++5YZxclv1BOjikufYuSwa0e
leq7qA5YG6kH
=3oLo
-----END PGP SIGNATURE-----

**Comment by aphyr** [comment]
Yeah, if it works in your env I'm happy to take a PR limiting the version. I'm sure the Beefcake folks would appreciate a ticket as well. :)

**Comment by peterneubauer** [comment]
See https://github.com/peterneubauer/riemann-ruby-client/compare/aphyr:master...patch-1?quick_pull=1

**Comment by aphyr** [comment]
Seeing another report of this problem from
